Rails.application.config.assets.precompile += %w( 'bootstrap.min' )
Rails.application.config.assets.precompile += %w( 'style' )
Rails.application.config.assets.precompile += %w( 'line-icons' )
Rails.application.config.assets.precompile += %w( 'font-awesome.min' )
Rails.application.config.assets.precompile += %w( 'page_log_reg_v1' )
Rails.application.config.assets.precompile += %w( 'default.min' )
Rails.application.config.assets.precompile += %w( 'custom' )
